- Makefile
The current `Makefile` works for CI (`goreleaser` command), but not locally if the `goreleaser` binary is not available, the `build` command should use `go build` with args so that the user can create the binary locally without additional dependencies.
- Changes the `build` command to use `go build...`
- Creates a `build-snapshot` command for use with goreleaser
- Adds a default command of `build` so when just `make` is used, the MCP is built
> fix: fix build in Makefile

- internal/buildkite/job_logs.go
- internal/buildkite/job_logs_test.go
- internal/commands/stdio.go
- add a `job_logs.go` internal file for getting job logs Buildkite builds
- add a `_test.go` for the same file with comprehensive testing
- add the command to the root `commands` file
Run `go test -run TestGetJobLogs ./... -v` for targeted test, or `go test ./... -v` for entire suite
> feat: add an action for getting job logs

- README.md
- Adds a YAML config example
- YAML config is used by [goose](https://block.github.io/goose/docs/getting-started/using-extensions#config-entry)
> Add YAML config

- .buildkite/Dockerfile.build
- .buildkite/docker-compose.yaml
- .goreleaser.yaml
- Dockerfile
- Dockerfile.local
- README.md
- allows user to run server via docker
- no longer need to  build to use
- updated README
- added `dockers` to `.goreleaser.yaml`
- included a `.local` Dockerfile for testing
```sh
docker build -t buildkite/buildkite-mcp-server:dev -f Dockerfile.local .
```
Set your config:
```json
{
"mcpServers": {
"buildkite": {
"command": "docker",
"args": [
"run",
"-i",
"--rm",
"-e",
"BUILDKITE_API_TOKEN",
"buildkite/buildkite-mcp-server:dev"
],
"env": {
"BUILDKITE_API_TOKEN": "bkua_xxxxxxxxxxxxx"
}
}
}
}
```
Re-launch Claude Desktop and you'll see that the `buildkite` MCP server is still available
> Dockerize MCP server

- README.md
- internal/buildkite/organizations.go
- internal/buildkite/organizations_test.go
- internal/commands/stdio.go
Also added a `user_token_organization_prompt` to encourage models to query this first when asked about buildkite pipelines and it worked 🤯 🙇🏻
> feat: added tool which returns the orginisation associated with a token

- internal/buildkite/buildkite.go
- internal/buildkite/buildkite_test.go
- internal/buildkite/builds_test.go
Currently, we set `30` builds as the default number that we look up when looking at a pipeline, however we could argue that unless specified, the most recent build is the only relevant one. If a user wants to more about their builds, they can ask something like _looking at the previous 5 builds..._.
The current default can mean that this MCP is reduced in value when we consider context length limits (tokens); 30 builds with just 8 steps each can easily blow out the context limits and cause a `400` response.
Given folks will be likely using this server in an IDE now that such a thing is supported, returning `400` responses during what is likely a debugging task is undesirable.
> reduce default builds to 1

- cmd/buildkite-mcp-server/main.go
- internal/trace/trace.go
At present the base url is fixed to api.buildkite.com , adding the option to specify different base URL along side with additional HTTP Headers ( useful cases like the api access is behind a proxy ) . 
**Test Plan :** Tested with a local build of the mcp server
> Add Support to specify the base URL and HTTP Headers in the MCP server

- internal/buildkite/cluster_queue.go
- internal/buildkite/cluster_queue_test.go
- internal/buildkite/clusters.go
- internal/buildkite/clusters_test.go
- internal/commands/stdio.go
As per #34 we need to list clusters so we can associate a queue to the pipeline at creation.
> feat: add read only access to clusters and cluster queues

- go.mod
- go.sum
- internal/buildkite/artifacts.go
- internal/buildkite/buildkite.go
- internal/buildkite/builds.go
- internal/buildkite/builds_test.go
- internal/buildkite/cluster_queue.go
- internal/buildkite/cluster_queue_test.go
- internal/buildkite/clusters.go
- internal/buildkite/clusters_test.go
- internal/buildkite/pipelines.go
- internal/buildkite/pipelines_test.go
I noticed that when i queried claude desktop about the state of my pipelines it would only list one, then summarise the results. 
To overcome this I added the `Link` header to all list results which contains the next, last page URLs and now it correctly collects all pipelines and summarises them.
There is scope to add other headers where needed in the future as well.
Also bumped the flags package.
> feat: add the link header to list results

- cmd/buildkite-mcp-server/main.go
- cmd/buildkite-mcp-server/main_test.go
When passing the custom tokens ( cases where BK Api is behind proxy , so needed to pass `Authorization: Bearer <jwt>` in header ) was able to see the token is not parsed correctly . 
When further debugged was able to see 
```
fmt.Sscanf doesn't treat : as a delimiter — it treats whitespace as a delimiter for %s. So it greedily grabs the entire "Authorization:" token first, leaving nothing to match the literal colon (:) in your format.
``` 
Fixing this using [strings.SplitN()](https://pkg.go.dev/strings#SplitN) 
Also added UT's to verify the behaviour
> Fix the Header Parsing with sending Custom Tokens

- README.md
Link new Buildkite API Access Token page with `read_pipelines` selected:
https://buildkite.com/user/api-access-tokens/new?scopes[]=read_pipelines
> Link to new token page with read_pipelines selected

- cmd/buildkite-mcp-server/main.go
- internal/commands/headers.go
- internal/commands/headers_test.go
Just moving things around to keep the main package as lean as possible.
> refactor: move the headers parser out to the command package

- .golangci.yml
- README.md
- cmd/update-docs/main.go
- internal/buildkite/joblogs/process_test.go
- internal/tokens/tokens.go
- internal/tokens/tokens_test.go
Just ensuring we have the standard linting in place for production.
> chore: enable gosec for security checking and gocritic for go conventions

- internal/buildkite/jobs.go
Our buildkite logfiles are routinely too large to handle directly by returning the log string to the LLM from tool invocation. This changeset reworks that tool to deal with that problem:
I tested it out with a pretty ordinary "the linter in a CI job says I messed up, please find the relevant job from my pr and fix it" prompt with good results on a couple of PRs. The only unfortunate piece of the UX here is that when we persist to a tempfile, LLM tools will typically need to toss up a trust prompt for `/tmp/wherever-mktemp-came-up-with`.
Full disclosure, I don't know go super well, so I did lean on claude-code for some of the details here, so please do let me know if anything needs to change.
I believe this'd also close #26 
Commit 2 adds support for mapping paths through via docker mounts …
> feat: Rework get_job_logs to handle very large logfiles

- internal/buildkite/builds.go
The `required` properties are at the wrong level on the env/metadata fields.
> Fix malformed json schema for `create_build` tool's input schema

- .buildkite/pipeline.release.yml
For the automated release introduced #40 we'd forgotten to add the required session tags
> Add session tags for the release pipeline

- internal/trace/trace.go
#77 bumped the otel package, but that caused it to start complaining about a mismatch in the semantic conventions schema.
> Update otel semconv to v1.34.0

- .buildkite/pipeline.release.yml
- .buildkite/release.sh
The ko documentation refers to GITHUB_TOKEN being handled automatically in https://ko.build/get-started/#authenticate but doesn't seem to be so, others are logging in explicity so adding that. https://github.com/MizuchiLabs/mantrae/blob/65bb32e28c897fb68cce0f2d66a378be8f057c14/.woodpecker/build.yaml#L37
> fix: add GHCR login during release to push images

- README.md
The editors and tools heading feels redundant, and "tools" is confusing when talking about MCP.
Zed doesn't need a louder heading and section than the other configurations.
> Tweak configuration in README

- internal/buildkite/artifacts.go
- internal/buildkite/artifacts_test.go
This commit implements URL rewriting functionality for artifact downloads to support custom Buildkite API base URLs (e.g., proxy configurations) using proper URL parsing instead of string manipulation.
Changes Made:
Enhanced BuildkiteClientAdapter.DownloadArtifactByURL()
- Added URL rewriting logic before downloading artifacts
- Calls new rewriteArtifactURL() method to handle URL transformation
Added rewriteArtifactURL() method with proper URL parsing
- Uses url.Parse() to parse both input and base URLs
- Compares host and scheme components directly
- Rewrites URLs when base URL differs from input URL
- Handles base URLs with path prefixes and trailing slashes
- Generic implementation without hardcoded domain assumptions
- Gracefully handles malformed URLs and nil/empty base URLs
Improved …
> feat: implement URL rewriting for artifact downloads with proper URL parsing

- README.md
We are now on the Docker MCP Hub!
https://hub.docker.com/mcp/server/buildkite/overview
This add a Add to Docker Desktop button (copied the link from the MCP hub) and a little not on usage.
> Add an Add to Docker Desktop button

- README.md
When I tried to configure the MCP in Goose, it crashed and honked, "should load extensions: Failed to deserialize value: invalid type: integer `2000`, expected a string" I'm guessing this would be needed in other tools as well.
> Update README to use token threshold value as a string

- .gitignore
A tiny one to avoid accidentally checking in debugger things from zed. I've also added it to my global gitignore, but it can be useful for others!
> Ignore zed config and zed debugger binaries

- pkg/buildkite/builds.go
- pkg/buildkite/builds_test.go
- pkg/server/mcp.go
* BuildSummary - Essential fields only (~85% token reduction)
* BuildDetail - Medium detail with job summary (~60% token reduction)
* BuildWithSummary - Maintained for backward compatibility
Also adds:
* Typed Args Structs for build related tools.
* Improved filtering for ListBuilds, with support for state, commit, creator and detail_level.
> refactor: revisit builds and reduce token use for common tasks

- README.md
People using the docker method were not getting updates on new releases, this resolves that and ensures they have a fresh version each time they start their agent.
Also moved to dockerhub as the default source of images as ghcr can be problematic for developers depending on configuration.
> docs: fix installation instructions to always update and use docker hub

- pkg/buildkite/access_token.go
- pkg/buildkite/annotations.go
- pkg/buildkite/artifacts.go
- pkg/buildkite/artifacts_test.go
- pkg/buildkite/cluster_queue.go
- pkg/buildkite/clusters.go
- pkg/buildkite/joblogs.go
- pkg/buildkite/organizations.go
- pkg/buildkite/organizations_test.go
- pkg/buildkite/pipelines.go
- pkg/buildkite/test_executions.go
- pkg/buildkite/test_executions_test.go
- pkg/buildkite/test_runs.go
- pkg/buildkite/test_runs_test.go
- pkg/buildkite/tests.go
- pkg/buildkite/user.go
This enables tracking of token use across tools using OTEL.
I have also gone through and removed some duplicate status checking, the underlying go-buildkite library already does this and returns an error structure for it, I also updated the tests verifying this behaviour.
> feat: add token tracking to otel and some cleanup of http errors
